<div id="app">
    <overlay
            ref="overlay"
    ></overlay>
    <popup
            ref="popup"
    ></popup>
    <newsletter
            ref="newsletter"
    ></newsletter>
</div>

<script type="text/x-magento-init">
    {
        "#app": {
            "BitbullNewsletter": {
                "subscribeActionUrl" : "<?php echo (string)$block->escapeUrl($block->getFormActionUrl()) ?>"
            }
        }
    }

</script>

